### ISSUE TITLE
Can't import AA120Q package

### ISSUE THREAD

**Issue by harper-carroll** [sisl/AA120Q#22]
Whenever I try to import AA120Q with 
`Pkg.add(PackageSpec(name="AA120Q", url="https://github.com/sisl/AA120Q.git"))
using AA120Q
`

I get the error:
`  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
[1mFetching: [========================================>]  100.0 %.0 %==========>                              ]  23.5 %]  46.8 %=============================>           ]  70.3 %]  93.6 % Resolving package versions...
 Installed StatsBase ─ v0.26.0
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [2913bbd2] ↑ StatsBase v0.25.0 ⇒ v0.26.0
  Updating git-repo `https://github.com/sisl/AA120Q.git`
[1mFetching: [========================================>]  100.0 %.0 % Resolving package versions...
┌ Info: Assigning UUID 91cbf3e6-4e4b-5d64-958a-11875e51d27a to AA120Q
└ @ Pkg.Types /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:724
  Updating `~/.julia/environments/v1.0/Project.toml`
  [91cbf3e6] ~ AA120Q v0.0.0 #master (https://github.com/sisl/AA120Q.git)
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [91cbf3e6] ~ AA120Q v0.0.0 #master (https://github.com/sisl/AA120Q.git)
  Building AA120Q → `~/.julia/packages/AA120Q/TWYJ6/deps/build.log`
┌ Error: Error building `AA120Q`: 
│ ERROR: LoadError: UndefVarError: Pkg not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/deps/build.jl:1
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
┌ Info: Precompiling AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a]
└ @ Base loading.jl:1186
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:85
**Failed to precompile AA120Q** [91cbf3e6-4e4b-5d64-958a-11875e51d27a] to /Users/harper/.julia/compiled/v1.0/AA120Q/ypfPZ.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[1]:4
`

I made some code edits to try to fix this, but they did not resolve this issue. Could someone help me out here?

**Comment by harper-carroll** [comment]
Here is one PR I made to try to fix this: https://github.com/sisl/AA120Q/pull/19

**Comment by mykelk** [comment]
I think the key is the `UndefVarError: @printf not defined`. You need `using Printf`.

**Comment by harper-carroll** [comment]
Hmm, unfortunately that doesn't solve it.

Running:
`import Pkg; Pkg.add("IJulia")
using Pkg
using Printf
Pkg.add(PackageSpec(name="AA120Q", url="https://github.com/sisl/AA120Q.git"))
using AA120Q`

I get the error message:
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
  Updating git-repo `https://github.com/sisl/AA120Q.git`
 Resolving package versions...
┌ Info: Assigning UUID 91cbf3e6-4e4b-5d64-958a-11875e51d27a to AA120Q
└ @ Pkg.Types /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:724
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
  Building AA120Q → `~/.julia/packages/AA120Q/TWYJ6/deps/build.log`
┌ Error: Error building `AA120Q`: 
│ ERROR: LoadError: UndefVarError: Pkg not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/deps/build.jl:1
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
┌ Info: Precompiling AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a]
└ @ Base loading.jl:1186
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:85
Failed to precompile AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a] to /Users/harper/.julia/compiled/v1.0/AA120Q/ypfPZ.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[3]:5

**Comment by harper-carroll** [comment]
Hmm, that doesn't solve it.

When I run:
![image](https://user-images.githubusercontent.com/20361958/49059721-07666a00-f1bf-11e8-90ec-07ee32796533.png)

I get the error message:
`┌ Info: Precompiling AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a]
└ @ Base loading.jl:1186
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:85
Failed to precompile AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a] to /Users/harper/.julia/compiled/v1.0/AA120Q/ypfPZ.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[8]:3
`

**Comment by mykelk** [comment]
I think you need to put it in the `AA120Q.jl` file.

**Comment by harper-carroll** [comment]
Still no luck. :(


`using Pkg; import AA120Q; using AA120Q`

Yields: 
┌ Info: Precompiling AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a]
└ @ Base loading.jl:1186
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import AA120Q; joinpath(dirname(pathof(AA120Q)), "..", paths...)`.
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:454
ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/cas_eval.jl:12
in expression starting at /Users/harper/.julia/packages/AA120Q/TWYJ6/src/AA120Q.jl:85
Failed to precompile AA120Q [91cbf3e6-4e4b-5d64-958a-11875e51d27a] to /Users/harper/.julia/compiled/v1.0/AA120Q/ypfPZ.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[2]:2

**Comment by harper-carroll** [comment]
Resolved with various updates across files to Julia 1.0.
